picklock:
  1:
    name: '&3PickLock'
    type: 'TRIPWIRE_HOOK'
    lore:
      - ' '
      - "&eUse this to pick lock other people's properties"
      - ' '
    chance: 10
  2:
    name: '&3PickLock'
    type: 'TRIPWIRE_HOOK'
    lore:
      - ' '
      - "&eUse this to pick lock other people's properties"
      - ' '
    chance: 20
  3:
    name: '&3PickLock'
    type: 'TRIPWIRE_HOOK'
    lore:
      - ' '
      - "&eUse this to pick lock other people's properties"
      - ' '
    chance: 30

countdown: 5
whitelisted:
  - 'world,54,34,2'